[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts =
    -v
    --strict-markers
    --alluredir=./reports/allure-results
    --clean-alluredir
    --reruns 1
    --reruns-delay 2
    --timeout=30

markers =
    smoke: smoke-тестов
    regression: регрессионных тестов
    api: Тесты API
    slow: Медленные тесты
    positive: Позитивные тесты
    negative: Негативные тесты
    auth: Тесты авторизации
    flaky: Ненадежные тесты