[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
filterwarnings =
    ignore:.*U.*mode is deprecated:DeprecationWarning

markers =
    smoke: smoke-тестов
    regression: регрессионных тестов
    api: Тесты API
    slow: Медленные тесты
    positive: Позитивные тесты
    negative: Негативные тесты
    auth: Тесты авторизации
    flaky: Ненадежные тесты